# Predicting Sales with Linear Regression

## Background

You and some friends created the ultimate child seat. It's a light and resistant seat that can be folded and stored in a backpack; it's the perfect solution for families traveling with children or people sharing their cars to take their kiddos to the school.

You want to spread the word about your invention, so you decided to run a digital marketing campaign using online ads. After running the campaign for a few days displaying different ads per day, you want to create a model to predict the expected sales depending on the number of ads you decide to show on the internet.

You realized that this is an excellent opportunity to use your linear regression skills to create a prediction model.

## Instructions

Follow the following steps to create a linear regression model to predict sales based on the historical data provided.

1. Load and visualize the sales data.

2. Prepare the data to fit the linear regression model.

3. Build the linear regression model using the `LinearRegression` module of Scikit-learn.

4. Plot the best fit line for the sales prediction model.

5. Use the linear regression model to predict the sales with 100 ads manually.

6. Make predictions using the `predict` function of the `LinearRegression` module.

7. Use the original data (the `X` and `y` sets) to assess the linear regression model using the score, r2, mse, rmse, and standard deviation metrics.

In [10]:
# Import required libraries
import numpy as np
import pandas as pd
import hvplot.pandas
from pathlib import Path
from sklearn.linear_model import LinearRegression

## Load and Visualize the Sales Data

In [11]:
# Read the sales data
file_path = Path("../Resources/sales.csv")
df_sales = pd.read_csv(file_path)

# Display sample data
df_sales.head()

ads  sales
0   21   8350
1  180  22820
2   50  12950
3  195  21105
4   96  15008

In [14]:
# Create a scatter plot with the sales information
sales_plot = df_sales.hvplot.scatter(
    x="ads",
    y="sales",
    title="Expected Sales Based on Total Number of Ads",
)
sales_plot

:Scatter   [ads]   (sales)

## Prepare the Data to Fit the Linear Regression Model

In [15]:
# Create the X set by using the `reshape` function to format the ads data as a single column array.
X = df_sales['ads'].values.reshape(-1,1)

# Display sample data
X[:5]

array([[ 21],
       [180],
       [ 50],
       [195],
       [ 96]], dtype=int64)

In [16]:
# Create an array for the dependent variable y with the sales data
y = df_sales['sales'].values.reshape(-1,1)
y[:5]

array([[ 8350],
       [22820],
       [12950],
       [21105],
       [15008]], dtype=int64)

## Build the Linear Regression Model

In [17]:
# Create a model with scikit-learn
model = LinearRegression()

In [18]:
# Fit the data into the model 
model.fit(X,y)

LinearRegression()

In [19]:
# Display the slope
print(f"Model's slope: {model.coef_}")

Model's slope: [[81.34898394]]


In [20]:
# Display the y-intercept
print(f"Model's y-intercept: {model.intercept_}")

Model's y-intercept: [7764.79694524]


In [21]:
# Display the model's best fit line formula
print(f"Model's formula: y = {model.intercept_} + {model.coef_[0]}X")

Model's formula: y = [7764.79694524] + [81.34898394]X


## Plot the Best Fit Line for the Sales Prediction Model

In [22]:
# Make predictions using the X set
predicted_y_values = model.predict(X)

In [25]:
# Create a copy of the original data
df_sales_predicted = df_sales.copy()

# Add a column with the predicted sales values
df_sales_predicted['salary_predicted'] = predicted_y_values

# Display sample data
df_sales_predicted.head()

ads  sales  salary_predicted
0   21   8350       9473.125608
1  180  22820      22407.614054
2   50  12950      11832.246142
3  195  21105      23627.848813
4   96  15008      15574.299403

In [27]:
# Create a line plot of the predicted salary values
best_fit_line = df_sales_predicted.hvplot.line(
    x = "ads", 
    y = 'salary_predicted', 
)
best_fit_line

:Curve   [ads]   (salary_predicted)

In [ ]:
# Superpose the original data and the best fit line
# YOUR CODE HERE

:Overlay
   .Scatter.I :Scatter   [ads]   (sales)
   .Curve.I   :Curve   [ads]   (sales_predicted)

## Make Manual Predictions

In [ ]:
# Display the formula to predict the sales with 100 ads
print(f"Model's formula: y = {model.intercept_} + {model.coef_[0]} * 100")

# Predict the sales with 100 ads
y_100 = # YOUR CODE HERE

# Display the prediction
print(f"Predicted sales with 100 ads: ${y_100:.2f}")

Model's formula: y = 7764.796945240416 + 81.34898393753775 * 100
Predicted sales with 100 ads: $15899.70


## Make Predictions Using the `predict` Function

In [ ]:
# Create an array to predict sales for 100, 150, 200, 250, and 300 ads
X_ads = # YOUR CODE HERE

# Format the array as a one-column array
X_ads = # YOUR CODE HERE

# Display sample data
X_ads

array([[100],
       [150],
       [200],
       [250],
       [300]])

In [ ]:
# Predict sales for 100, 150, 200, 250, and 300 ads
predicted_sales = # YOUR CODE HERE

In [ ]:
# Create a DataFrame for the predicted sales
# YOUR CODE HERE

# Display data
# YOUR CODE HERE

ads  predicted_sales
0  100     15899.695339
1  150     19967.144536
2  200     24034.593733
3  250     28102.042930
4  300     32169.492127

## Assess the Linear Regression Model

In [ ]:
# Import relevant metrics from scikit-learn: score, r2, mse, rmse, std
from sklearn.metrics import mean_squared_error, r2_score

In [ ]:
# Compute the metrics for the linear regression model
score = # YOUR CODE HERE
r2 = # YOUR CODE HERE
mse = # YOUR CODE HERE
rmse = # YOUR CODE HERE
std = # YOUR CODE HERE

# Print releveant metrics.
print(f"The score is {score}.")
print(f"The r2 is {r2}.")
print(f"The mean squared error is {mse}.")
print(f"The root mean squared error is {rmse}.")
print(f"The standard deviation is {std}.")

The score is 0.9219961974942595.
The r2 is 0.9219961974942595.
The mean squared error is 1922652.7853956919.
The root mean squared error is 1386.5975571144252.
The standard deviation is 4964.6946616416735.
